#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
	public:
		DWORD	dwType;
		BYTE    bApplyOn;
		long    lApplyValue;
		DWORD   dwFlag;
		long	lDuration;
		long	lSPCost;

		static CAffect* Acquire();
		static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED		= 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
#ifdef ENABLE_WOLFMAN_CHARACTER
	AFFECT_BLEEDING,		// 227
#endif
#ifdef __NEWPET_SYSTEM__
	AFFECT_PET,				// 228
#endif
	AFFECT_PREMIUM_START	= 500,
	AFFECT_EXP_BONUS		= 500,	// °æÇèÀÇ ¹ÝÁö
	AFFECT_ITEM_BONUS		= 501,	// µµµÏÀÇ Àå°©
	AFFECT_SAFEBOX		= 502,  // PREMIUM_SAFEBOX,
	AFFECT_AUTOLOOT		= 503,	// PREMIUM_AUTOLOOT,
	AFFECT_FISH_MIND		= 504,	// PREMIUM_FISH_MIND,
	AFFECT_MARRIAGE_FAST	= 505,	// ¿ø¾ÓÀÇ ±êÅÐ
	AFFECT_GOLD_BONUS		= 506,	// µ· µå·ÓÈ®·ü 50%Áõ°¡
	AFFECT_PREMIUM_END		= 509,

	AFFECT_MALL			= 510,	// ¸ô ¾ÆÀÌÅÛ ¿¡ÆåÆ®
	AFFECT_NO_DEATH_PENALTY	= 511,	// ¿ë½ÅÀÇ °¡È£ (°æÇèÄ¡°¡ ÆÐ³ÎÆ¼¸¦ ÇÑ¹ø ¸·¾ÆÁØ´Ù)
	AFFECT_SKILL_BOOK_BONUS	= 512,	// ¼±ÀÎÀÇ ±³ÈÆ (Ã¥ ¼ö·Ã ¼º°ø È®·üÀÌ 50% Áõ°¡)
	AFFECT_SKILL_NO_BOOK_DELAY	= 513,	// ÁÖ¾È¼ú¼­

	AFFECT_HAIR	= 514,	// Çì¾î È¿°ú
	AFFECT_COLLECT = 515, //¼öÁýÄù½ºÆ®
	AFFECT_EXP_BONUS_EURO_FREE = 516, // °æÇèÀÇ ¹ÝÁö (À¯·´ ¹öÀü 14 ·¹º§ ÀÌÇÏ ±âº» È¿°ú)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

#if defined(ENABLE_NEW_AUTOPOTION)
	AFFECT_AUTO_ATTACK_SPEED_RECOVERY = 850, /* 850 + 20 = 870 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_MOV_SPEED_RECOVERY = 851,    /* 851 + 20 = 871 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_CRITICAL_RECOVERY = 852,     /* 852 + 20 = 872 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_PENETRATE_RECOVERY = 853,    /* 853 + 20 = 873 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_VIT_RECOVERY = 854,          /* 854 + 20 = 874 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_STR_RECOVERY = 855,          /* 855 + 20 = 875 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_INT_RECOVERY = 856,          /* 856 + 20 = 876 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_DEX_RECOVERY = 857,          /* 857 + 20 = 877 (COMPRUEBE QUE LO TENGA DISPONIBLE) */

	AFFECT_AUTO_RED_POTION_RECOVERY = 858,  /* 858 + 20 = 877 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_ORANGE_POTION_RECOVERY = 859,  /* 858 + 20 = 877 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_YELLOW_POTION_RECOVERY = 860,  /* 858 + 20 = 877 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_GREEN_POTION_RECOVERY = 861,  /* 858 + 20 = 877 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_BLUE_POTION_RECOVERY = 862,  /* 858 + 20 = 877 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
	AFFECT_AUTO_WHITE_POTION_RECOVERY = 863,  /* 863 + 20 = 883 (COMPRUEBE QUE LO TENGA DISPONIBLE) */
#endif


	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

#ifdef ENABLE_BIOLOG_SYSTEM
	AFF_BIO_1 = 543,	AFF_BIO_2 = 544,	AFF_BIO_3 = 545,	AFF_BIO_4 = 546,
	AFF_BIO_5 = 547,	AFF_BIO_6 = 548,	AFF_BIO_7 = 549,	AFF_BIO_8 = 550,
	AFF_BIO_9 = 551,	AFF_BIO_10 = 552,	AFF_BIO_11 = 553,	AFF_BIO_12 = 554,
	AFF_BIO_13 = 555,	AFF_BIO_14 = 556,	AFF_BIO_15 = 557,	AFF_BIO_16 = 558,
	AFF_BIO_17 = 559,	AFF_BIO_18 = 560,	AFF_BIO_19 = 561,	AFF_BIO_20 = 562,
#endif
#ifdef __NEWPET_SYSTEM__
	AFFECT_NEW_PET = 563,
#endif
	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING	   = 301,

	AFFECT_NOG_ABILITY = 302,
	

	AFFECT_HOLLY_STONE_POWER = 303,

#ifdef ENABLE_NEW_AFFECT_POTION
	AFFECT_POTION_1 = 303,
	AFFECT_POTION_2 = 304,
	AFFECT_POTION_3 = 305,
	AFFECT_POTION_4 = 306,
	AFFECT_POTION_5 = 307,
	AFFECT_POTION_6 = 308,

	//Affect Cristal//
	AFFECT_POTION_7 = 309,
	AFFECT_POTION_8 = 310,
	AFFECT_POTION_9 = 311,
	AFFECT_POTION_10 = 312,
	AFFECT_POTION_11 = 313,

#endif

#if defined(WJ_COMBAT_ZONE)	
	AFFECT_COMBAT_ZONE_POTION = 585,
	AFFECT_COMBAT_ZONE_DEFENSE = 586,
	AFFECT_COMBAT_ZONE_MOVEMENT = 587,
	AFFECT_COMBAT_ZONE_MOB = 588,
#endif

#ifdef BATTLEPASS_WORLDARD
	AFFECT_BATTLE_PASS = 600,
#endif
#ifdef ENABLE_CONQUEROR_LEVEL
	AFFECT_SUNGMA_STR	= 907,
	AFFECT_SUNGMA_HP	= 908,
	AFFECT_SUNGMA_MOVE	= 909,
	AFFECT_SUNGMA_INMUNE	= 910,
#endif
#ifdef ENABLE_OFFLINESHOP_SYSTEM
	AFFECT_DECORATION = 703,
#endif
#ifdef ENABLE_MULTI_FARM_BLOCK
	AFFECT_MULTI_FARM_PREMIUM = 704,
#endif
#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFFECT_STATUE = 700,
#endif

#ifdef ENABLE_AUTOMATIC_PICK_UP_SYSTEM
	AFFECT_AUTO_PICK_UP = 705,
#endif
#ifdef ENABLE_VOTE4BUFF
	AFFECT_VOTE4BUFF = 809,
#endif
	AFFECT_QUEST_START_IDX = 1000,

};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,		// ´øÀü¿¡¼­ ÁØºñ »óÅÂ
	AFF_DUNGEON_UNIQUE,		// ´øÀü À¯´ÏÅ© (Å¬¶óÀÌ¾ðÆ®¿¡¼­ ÄÃ¸µµÇÁö¾ÊÀ½)

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,

	AFF_JEONGWIHON,		// Àü±ÍÈ¥
	AFF_GEOMGYEONG,		// °Ë°æ
	AFF_CHEONGEUN,		// Ãµ±ÙÃß
	AFF_GYEONGGONG,		// °æ°ø¼ú
	AFF_EUNHYUNG,		// ÀºÇü¹ý
	AFF_GWIGUM,			// ±Í°Ë
	AFF_TERROR,			// °øÆ÷
	AFF_JUMAGAP,		// ÁÖ¸¶°©
	AFF_HOSIN,			// È£½Å
	AFF_BOHO,			// º¸È£
	AFF_KWAESOK,		// Äè¼Ó
	AFF_MANASHIELD,		// ¸¶³ª½¯µå
	AFF_MUYEONG,		// ¹«¿µÁø affect
	AFF_REVIVE_INVISIBLE,	// ºÎÈ°½Ã Àá½Ãµ¿¾È ¹«Àû
	AFF_FIRE,			// Áö¼Ó ºÒ µ¥¹ÌÁö
	AFF_GICHEON,		// ±âÃµ´ë°ø
	AFF_JEUNGRYEOK,		// Áõ·Â¼ú
	AFF_TANHWAN_DASH,		// ÅºÈ¯°Ý¿ë ´Þ¸®±â¾îÆåÆ®
	AFF_PABEOP,			// ÆÄ¹ý¼ú
	AFF_CHEONGEUN_WITH_FALL,	// Ãµ±ÙÃß
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,
	AFF_HAIR,	// Çì¾î
	AFF_GERMANY, // µ¶ÀÏ
	AFF_RAMADAN_RING,

#ifdef ENABLE_WOLFMAN_CHARACTER
	AFF_BLEEDING,			// 42
	AFF_RED_POSSESSION,		// 44
	AFF_BLUE_POSSESSION,	// 43
#endif
#ifdef ENABLE_CONQUEROR_LEVEL
	AFF_CHEONUN = 46,
	AFF_CHUNWOON_MOOJUK = 47,
#endif
#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,
#endif

	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect * pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect°¡ ¹«ÇÑ´ë·Î µé¾î°¡ ÀÖ¾î¾ß ÇÒ °æ¿ì »ç¿ë.
	// ½Ã°£À» °è¼Ó ÁÙÀÌ±â ¶§¹®¿¡ ¸Å¿ì Å«°ªÀ¸·Î ¹«ÇÑ´ë¸¦ ¿¡¹Ä·¹ÀÌ¼ÇÇÔ.
	//// 24ºñÆ®´Â ÀûÀ¸¹Ç·Î 25ºñÆ®¸¦ »ç¿ë.
	// ... 25ºñÆ® »ç¿ëÇÑ´Ù°í ÇØ³õ°í¼± 29bit »ç¿ëÇÏ°í ÀÖ´Â ¾öÃ»³­ ÁÖ¼®ÀÌ¶õ...
	// collect quest¿¡¼­ ¹«ÇÑ ½Ã°£À» 60³âÀ¸·Î »ç¿ëÇÏ°í ÀÖÀ¸¹Ç·Î, ¿©±âµµ 60³âÀ¸·Î ÇÏÀÚ.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
